# Fake News Classifier Using LSTM

In [23]:
# Import Dependencies
import tensorflow as tf 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

In [1]:
import pandas as pd 

df = pd.read_csv("fake_news.csv")
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [2]:
# Check the null values
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [3]:
# Drop Nan values
df = df.dropna()

In [5]:
# Get th Independent Features and dependent feature
X = df.drop("label" , axis=1)
y = df.label


In [6]:
X.shape , y.shape

((18285, 4), (18285,))

## One-Hot Representation

In [8]:
# Vocabulary size
voc_size=5000

In [9]:
messages = X.copy()

In [10]:
messages["title"][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [11]:
messages["text"][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide, it looks like we also know who the second-worst person is as well. It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey. They found out via a tweet from one of the Republican committee chairmen. \nAs we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewing emai

In [12]:
messages.reset_index(inplace=True)

In [13]:
# import Dependencies for NLP task
import nltk
import re
from nltk.corpus import stopwords

In [14]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [17]:
# Data Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

1
14952
14953
14954
14955
14956
14957
14958
14959
14960
14961
14962
14963
14964
14965
14966
14967
14968
14969
14970
14971
14972
14973
14974
14975
14976
14977
14978
14979
14980
14981
14982
14983
14984
14985
14986
14987
14988
14989
14990
14991
14992
14993
14994
14995
14996
14997
14998
14999
15000
15001
15002
15003
15004
15005
15006
15007
15008
15009
15010
15011
15012
15013
15014
15015
15016
15017
15018
15019
15020
15021
15022
15023
15024
15025
15026
15027
15028
15029
15030
15031
15032
15033
15034
15035
15036
15037
15038
15039
15040
15041
15042
15043
15044
15045
15046
15047
15048
15049
15050
15051
15052
15053
15054
15055
15056
15057
15058
15059
15060
15061
15062
15063
15064
15065
15066
15067
15068
15069
15070
15071
15072
15073
15074
15075
15076
15077
15078
15079
15080
15081
15082
15083
15084
15085
15086
15087
15088
15089
15090
15091
15092
15093
15094
15095
15096
15097
15098
15099
15100
15101
15102
15103
15104
15105
15106
15107
15108
15109
15110
15111
15112
15113
15114
15115
15116
15117
15

In [18]:
corpus

chut new york time',
 'stranahan steve bannon nail media fight trump breitbart',
 'texa elector expect massiv corrupt relat elector colleg vote',
 'guilti power nullif counteract govern tyranni',
 'trillion new debt day',
 'tori councillor say homeless peopl elimin',
 'review hillbilli elegi tough love analysi poor back trump new york time',
 'crimin chief',
 'govern lie movi',
 'trump brexit defeat global anyway',
 'face congress sport offici begin confront sexual abus new york time',
 'airbnb end fight new york citi fine new york time',
 'big pharma martin shkreli suspend twitter breitbart',
 'next big tech corridor seattl vancouv planner hope new york time',
 'evid robot win race american job new york time',
 'see africa road new york time',
 'happen hip hop hillari goe dead broke brace',
 'bill maher high trump state free speech new era new york time',
 'l p g tour donald trump complic new york time',
 'legend art cashin trump presid new world order gold brexit great depress see pa

In [20]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

28,
  1748,
  1951,
  9,
  3821,
  280,
  1339,
  1435,
  3352,
  427,
  2684,
  3285],
 [3205, 519, 2669, 3794, 1914],
 [354, 2785, 3849, 4739, 1766, 1976, 2882, 115, 1977],
 [649, 426, 2011, 2355, 176, 1341],
 [3499, 513, 1111, 4302, 3445, 2882, 4692, 4904, 2925, 2304, 2497, 4940],
 [3417, 2535, 431, 692],
 [4903, 4659, 4549, 203, 738, 960, 3325, 4666],
 [4470, 2688, 4772, 4106, 486, 1218, 4336, 2882, 115, 1977],
 [2251, 2778, 284, 3366, 1154, 2198, 4360, 3413],
 [2943, 2891, 2943, 669, 3946, 1278],
 [1439, 286, 836, 985, 3345, 3137, 244, 279, 2511, 2882, 115, 1977],
 [128, 1529, 627, 1066, 1787, 1920, 2947, 2116, 951, 2882, 115, 1977],
 [3686, 317, 948, 3197, 3235, 326, 3754, 1379],
 [3224, 4615, 627, 3119, 2550, 1493, 2545, 2690, 2882, 115, 1977],
 [3805, 2284, 3774, 3849, 823],
 [955, 1782, 541, 4586, 4136, 3053, 2405, 1863, 4656, 2882, 115, 1977],
 [2850, 3503, 2199, 2910, 1715, 1453, 576, 4455, 4141],
 [3071, 3622, 203, 2982, 819, 2268, 3417],
 [716, 4302, 4522, 2015, 3417, 3758

## Embedding Representation

In [21]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr , padding="pre" , maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 2763 2424  744]
 [   0    0    0 ... 3983 2595 3285]
 [   0    0    0 ... 4347 3830 4431]
 ...
 [   0    0    0 ... 2882  115 1977]
 [   0    0    0 ... 4055 2601 4695]
 [   0    0    0 ... 1706 4906  853]]


In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2208,
        795, 2947, 1186, 3496, 1055, 3485, 2763, 2424,  744])

In [24]:
# Creating model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size , embedding_vector_features , input_length = sent_length))
model.add(LSTM(100)) # one LSTM layer with 100 neurons
model.add(Dense(1 , activation = "sigmoid"))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(loss="binary_crossentropy" , optimizer = "adam" , metrics=["accuracy"])

In [27]:
len(embedded_docs) , y.shape

(18285, (18285,))

In [28]:
import numpy as np 
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [29]:
X_final.shape , y.shape

((18285, 20), (18285,))

In [30]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X_final , y_final , test_size=0.33 , random_state=42)


## Training the model

In [31]:
model.fit(X_train , y_train , validation_data=(X_test , y_test) , epochs=10 , batch_size = 64)

Epoch 1/10
192/192 [==============================] - 13s 69ms/step - loss: 0.3347 - accuracy: 0.8472 - val_loss: 0.1999 - val_accuracy: 0.9104
Epoch 2/10
192/192 [==============================] - 14s 73ms/step - loss: 0.1396 - accuracy: 0.9477 - val_loss: 0.2005 - val_accuracy: 0.9200
Epoch 3/10
192/192 [==============================] - 11s 57ms/step - loss: 0.0912 - accuracy: 0.9653 - val_loss: 0.2284 - val_accuracy: 0.9191
Epoch 4/10
192/192 [==============================] - 11s 55ms/step - loss: 0.0596 - accuracy: 0.9787 - val_loss: 0.2839 - val_accuracy: 0.9142
Epoch 5/10
192/192 [==============================] - 11s 56ms/step - loss: 0.0367 - accuracy: 0.9876 - val_loss: 0.3295 - val_accuracy: 0.9137
Epoch 6/10
192/192 [==============================] - 10s 54ms/step - loss: 0.0212 - accuracy: 0.9933 - val_loss: 0.4120 - val_accuracy: 0.9118
Epoch 7/10
192/192 [==============================] - 11s 55ms/step - loss: 0.0131 - accuracy: 0.9958 - val_loss: 0.4608 - val_accuracy:

## Check the Metrics and Accuracy

In [42]:
y_pred = model.predict_classes(X_test)

In [48]:
y_test[:10]

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1], dtype=int64)

In [43]:
y_pred[:10]

array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])

In [45]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[3140,  279],
       [ 302, 2314]], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.903728251864126

### If we are adding the Dropout layer 

In [49]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [50]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 13s 65ms/step - loss: 0.3458 - accuracy: 0.8308 - val_loss: 0.2164 - val_accuracy: 0.9117
Epoch 2/10
192/192 [==============================] - 10s 54ms/step - loss: 0.1513 - accuracy: 0.9389 - val_loss: 0.1972 - val_accuracy: 0.9171
Epoch 3/10
192/192 [==============================] - 11s 56ms/step - loss: 0.1099 - accuracy: 0.9589 - val_loss: 0.2137 - val_accuracy: 0.9147
Epoch 4/10
192/192 [==============================] - 10s 53ms/step - loss: 0.0855 - accuracy: 0.9675 - val_loss: 0.2659 - val_accuracy: 0.9173
Epoch 5/10
192/192 [==============================] - 11s 55ms/step - loss: 0.0610 - accuracy: 0.9779 - val_loss: 0.2691 - val_accuracy: 0.9191
Epoch 6/10
192/192 [==============================] - 11s 55ms/step - loss: 0.0470 - accuracy: 0.9834 - val_loss: 0.3002 - val_accuracy: 0.9133
Epoch 7/10
192/192 [==============================] - 11s 59ms/step - loss: 0.0335 - accuracy: 0.9886 - val_loss: 0.3352 - val_accuracy:

In [51]:
y_pred=model.predict_classes(X_test)

In [52]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[3147,  272],
       [ 282, 2334]], dtype=int64)

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9082021541010771

Accuracy is much more better if we add the Dropout layer 